import type { Floor, RoomDef } from "../types";

/**
 * The manor's rooms. `start` tiles are pre-placed; the rest form the shuffled
 * room deck and are drawn as players push through unexplored doorways.
 *
 * Every room must declare at least one doorway so it can connect back to the
 * tile it was entered from. All names and flavor are original to this project.
 */

const ALL: Floor[] = ["basement", "ground", "upper"];

export const ROOMS: RoomDef[] = [
  // --- Starting tiles (pre-placed, central stair hub) ---
  {
    id: "entrance-hall",
    name: "Entrance Hall",
    floors: ["ground"],
    doorways: ["north"],
    special: "entrance-hall",
    start: true,
    flavor: "The door slams shut behind you. Of course it does.",
  },
  {
    id: "foyer",
    name: "Foyer",
    floors: ["ground"],
    doorways: ["north", "south", "east", "west"],
    special: "foyer",
    start: true,
    flavor: "A grand room gone to mildew. Four ways onward, none inviting.",
  },
  {
    id: "grand-staircase",
    name: "Grand Staircase",
    floors: ["ground"],
    doorways: ["south"],
    special: "grand-staircase",
    start: true,
    flavor: "Stairs climb into the dark above and descend into worse below.",
  },
  {
    id: "upper-landing",
    name: "Upper Landing",
    floors: ["upper"],
    doorways: ["south", "east", "west"],
    special: "stairs-down",
    start: true,
    flavor: "The boards up here remember every footstep ever taken on them.",
  },
  {
    id: "basement-landing",
    name: "Basement Landing",
    floors: ["basement"],
    doorways: ["north", "east", "west"],
    special: "stairs-up",
    start: true,
    flavor: "The air is wet and tastes of old pennies.",
  },

  // --- Drawable rooms ---
  {
    id: "dusty-hallway",
    name: "Dusty Hallway",
    floors: ALL,
    doorways: ["north", "south"],
    special: "none",
    flavor: "Your footprints are the only ones in decades of dust. You hope.",
  },
  {
    id: "creaking-corridor",
    name: "Creaking Corridor",
    floors: ALL,
    doorways: ["north", "east", "south", "west"],
    special: "none",
    flavor: "Something creaks. Then stops, as if listening for you.",
  },
  {
    id: "portrait-gallery",
    name: "Portrait Gallery",
    floors: ["ground", "upper"],
    doorways: ["north", "south", "east"],
    symbol: "event",
    special: "none",
    flavor: "The eyes follow you. You tell yourself it's just good painting.",
  },
  {
    id: "abandoned-nursery",
    name: "Abandoned Nursery",
    floors: ["upper"],
    doorways: ["south", "west"],
    symbol: "omen",
    special: "none",
    flavor: "A music box turns by itself, one note at a time.",
  },
  {
    id: "servants-quarters",
    name: "Servants' Quarters",
    floors: ["ground", "upper"],
    doorways: ["north", "east"],
    symbol: "item",
    special: "none",
    flavor: "Cots still made. Whoever left did so in a hurry.",
  },
  {
    id: "larder",
    name: "Larder",
    floors: ["ground", "basement"],
    doorways: ["north", "west"],
    symbol: "event",
    special: "none",
    flavor: "Jars of something dark. The labels have all peeled away.",
  },
  {
    id: "cold-cellar",
    name: "Cold Cellar",
    floors: ["basement"],
    doorways: ["north", "east", "south"],
    symbol: "item",
    special: "none",
    flavor: "Your breath fogs. It is colder here than outside ever was.",
  },
  {
    id: "boiler-room",
    name: "Boiler Room",
    floors: ["basement"],
    doorways: ["north", "west"],
    symbol: "event",
    special: "drain-speed",
    flavor: "The boiler is stone cold, yet the pipes still groan and knock.",
  },
  {
    id: "catacomb",
    name: "Catacomb",
    floors: ["basement"],
    doorways: ["north", "east", "south", "west"],
    symbol: "omen",
    special: "none",
    flavor: "Niches in the wall, each the size of a person. Most are occupied.",
  },
  {
    id: "chapel",
    name: "Chapel",
    floors: ["ground", "upper"],
    doorways: ["north", "south"],
    symbol: "omen",
    special: "heal-sanity",
    aura: 1,
    flavor: "A small altar. Whatever was worshipped here, it wasn't merciful.",
  },
  {
    id: "conservatory",
    name: "Conservatory",
    floors: ["ground"],
    doorways: ["north", "east", "west"],
    symbol: "event",
    special: "none",
    flavor: "Dead plants, every one of them turned to face the same window.",
  },
  {
    id: "study",
    name: "Study",
    floors: ["ground", "upper"],
    doorways: ["south", "east"],
    symbol: "item",
    special: "none",
    flavor: "An open journal, the last entry a single word repeated to the margin.",
  },
  {
    id: "master-bedroom",
    name: "Master Bedroom",
    floors: ["upper"],
    doorways: ["north", "south", "west"],
    symbol: "omen",
    special: "none",
    flavor: "The bed is unmade and still warm. You are quite alone.",
  },
  {
    id: "attic",
    name: "Attic",
    floors: ["upper"],
    doorways: ["south"],
    symbol: "omen",
    special: "pit",
    flavor: "Rafters vanish into black. Something up there shifts its weight.",
  },
  {
    id: "kitchen",
    name: "Kitchen",
    floors: ["ground", "basement"],
    doorways: ["north", "east", "south"],
    symbol: "event",
    special: "heal-might",
    flavor: "Knives hang in a neat row. One is missing.",
  },
  {
    id: "dining-room",
    name: "Dining Room",
    floors: ["ground"],
    doorways: ["north", "east", "south", "west"],
    symbol: "event",
    special: "none",
    flavor: "The table is set for far more guests than ever arrived.",
  },
  {
    id: "library",
    name: "Library",
    floors: ["ground", "upper"],
    doorways: ["north", "south", "east"],
    symbol: "item",
    special: "none",
    flavor: "Ten thousand books, and every one of them about this house.",
  },
  {
    id: "crypt",
    name: "Crypt",
    floors: ["basement"],
    doorways: ["north", "south"],
    symbol: "omen",
    special: "none",
    aura: -1,
    flavor: "A single sarcophagus, lid slid just slightly ajar.",
  },
  {
    id: "mystic-elevator",
    name: "Mystic Elevator",
    floors: ALL,
    doorways: ["north", "east", "south", "west"],
    special: "mystic-elevator",
    flavor: "A cage of black iron. The dial spins on its own.",
  },
  {
    id: "gymnasium",
    name: "Gymnasium",
    floors: ["ground", "upper"],
    doorways: ["north", "west"],
    symbol: "event",
    special: "heal-might",
    flavor: "Rotting exercise equipment, and chalk handprints far too high up.",
  },
  {
    id: "vault",
    name: "Vault",
    floors: ALL,
    doorways: ["north"],
    symbol: "item",
    special: "vault",
    flavor: "A great steel door, shut tight. It wants a key. It wants more.",
  },
  {
    id: "pentagram-chamber",
    name: "Pentagram Chamber",
    floors: ["basement"],
    doorways: ["north", "east", "south", "west"],
    symbol: "omen",
    special: "draw-extra-omen",
    aura: -1,
    flavor: "The figure on the floor is painted in something that isn't paint.",
  },
];

export const ROOMS_BY_ID: Record<string, RoomDef> = Object.fromEntries(
  ROOMS.map((r) => [r.id, r]),
);

export const START_ROOMS = ROOMS.filter((r) => r.start);
export const DRAWABLE_ROOMS = ROOMS.filter((r) => !r.start);
